## Machine Learning

![image](https://media.licdn.com/dms/image/v2/C5112AQGFmiO6MpHbBQ/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1586790931639?e=1772064000&v=beta&t=o3wm0CcNT8ckoWk2EbflCO4yI7khJm759XqCUGjVN3I)

![image](https://framerusercontent.com/images/wZu4PgwNVYmOPSMoJYydbuTVs.png?width=1240&height=1764)

![image](https://developer.ibm.com/developer/default/articles/cc-models-machine-learning/images/figure01.png)

### Application
- Recommendation Engine : Netflix viewing suggestion ( Media + Entertainment + Shopping)
- Self Driving Car : Automotive + Transportation
- Mobile Application : Learning Language Application
- Muntra : Fashion E-Commerce
- Oerderly HEalth : Healthcare

### Machine learning Life Cycle
1. Data Collection: Gather raw data from databases, APIs, sensors, files, etc.
2. Data Preparation: Clean basic issues like missing values, duplicates, formatting.
3. Data Wrangling: Transform and engineer features to make data ML-ready.
4. Data Modelling: Choose the suitable ML algorithm for the problem.
5. Model Training: Train the model using training data.
6. Model testing: Evaluate model performance using test/validation data.
7. Deployment: Deploy the model to real-world applications.

### AI v/s ML v/s DL

- (((DL) > ML) > AL)
- AI: making computer capable enough to perform the task
- ML: enables machine to learn from past dataset without being explicitly programmed
    - supervised : label dataset
    - unsupervised : unlabel dataset
    - reinforcement : बक्षीस आणि शिक्षा यावरून शिकणे
- DL: algorithm inspired by the structure and function of human brains (neural network)

## Data Pre-processing: 
### process of converting your raw data into the suitable form
#### steps involved while performing:
1. Getting dataset
2. importing libraries
3. importing Datasets
4. Finding missing values
5. Encoding categorical data
6. Splitig Dataset into Training & Test Set
7. Feature Scaling

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('/Users/rahulg/Downloads/python-revision-experiments/4.csv_files/Data.csv')
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
x = df[['Country', 'Age', 'Salary']]
x

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [ ]:
x = df[['Country', 'Age', 'Salary']].values # array set
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [5]:
y = df['Purchased']
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: str

In [ ]:
y = df['Purchased'].values # array set
y

<StringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str