# Pandas

- used to data manipulate and analysis
- effective on structure data like table based one's

In [5]:
!pip install pandas
!pip install --upgrade pip

Collecting pandas
  Downloading pandas-3.0.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 1.0 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numpy>=1.26.0 in /Users/rahulg/Downloads/python-revision-experiments/.venv/lib/python3.12/site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rahulg/Downloads/python-revision-experiments/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/rahulg/Downloads/python-revision-experiments/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp312-cp312-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 5.7 MB/s eta 0:00:0000:0100:01
Installing collected packages: pandas
Successfully installed pandas-3.0.0

[notice] A new release of pip is available: 24.0 -> 26.0
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: pip in /Users/rahulg/Downloads/python-revision-experiments/.venv/lib/python3.12/site-packages (24.0)
Collecting pip
  Downloading pip-26.0-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-26.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.2 MB/s eta 0:00:0000:0100:01
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0
Successfully installed pip-26.0

In [1]:
# import pandas as pd
import pandas as pd

In [8]:
# check the version of pandas

print(pd.__version__)

3.0.0

### Dataframe

- frame that has rows and column

- Extra information: Shift + Tab (enables the code writing info) [HP]
- In MacOS : Cmd + shift + space

In [9]:
df = pd.DataFrame([1,2,3])
print(df)

   0
0  1
1  2
2  3

In [12]:
df = pd.DataFrame([11,22,33], columns= ["Col_Name"])
print(df)
#          column
#   row      0
#    0.      11
#    1.      22
#    2.      33

print(type(df))

   Col_Name
0        11
1        22
2        33
<class 'pandas.DataFrame'>

### creating Dataframe

In [3]:
data = {
    'Name' : ["Rahul", "Janvi","Aishwarya","Simran"],
    "Age" : [16,17,18,19],
    "Salary" : [90000, 70000, 50000, 30000]
}

df = pd.DataFrame(data)
print(df)
print(type(df))

        Name  Age  Salary
0      Rahul   16   90000
1      Janvi   17   70000
2  Aishwarya   18   50000
3     Simran   19   30000
<class 'pandas.DataFrame'>

### Basic Dataframe Understanding

In [34]:
df.head(2) # top rows

    Name  Age  Salary
0  Rahul   16   90000
1  Janvi   17   70000

In [36]:
df.tail(2) # last rows

        Name  Age  Salary
2  Aishwarya   18   50000
3     Simran   19   30000

In [20]:
df.shape # tells row x column

(4, 3)

In [21]:
df.columns # columns name

Index(['Name', 'Age', 'Salary'], dtype='str')

In [37]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace= True) # rename of the column

# use of inplace = True {made changes in the origin data}

In [38]:
df

        Name  Age  Monthly_Salary
0      Rahul   16           90000
1      Janvi   17           70000
2  Aishwarya   18           50000
3     Simran   19           30000

In [39]:
df.info() # infomation about the table

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [32]:
df.describe() # statistical summary of the table

             Age  Monthly_Salary
count   4.000000        4.000000
mean   17.500000    60000.000000
std     1.290994    25819.888975
min    16.000000    30000.000000
25%    16.750000    45000.000000
50%    17.500000    60000.000000
75%    18.250000    75000.000000
max    19.000000    90000.000000

### Save and load data from csv

In [ ]:
df.to_csv('testData.csv', index= False) # export into csv & also removed the index out of it

In [8]:
loaddf = pd.read_csv('testData.csv') # import from csv 
loaddf

        Name  Age  Salary
0      Rahul   16   90000
1      Janvi   17   70000
2  Aishwarya   18   50000
3     Simran   19   30000

### Rows and Column Selection

In [9]:
# select column

df['Name'] # single column

0        Rahul
1        Janvi
2    Aishwarya
3       Simran
Name: Name, dtype: str

In [11]:
df[['Name','Salary']]   # mutiple columns

        Name  Salary
0      Rahul   90000
1      Janvi   70000
2  Aishwarya   50000
3     Simran   30000

In [14]:
# slect rows. : loc = label based index 
df.loc[df.Name=="Janvi"]    # location index based on name

df.loc[(df.Name=='Rahul') & (df.Salary>= 50000)]

    Name  Age  Salary
0  Rahul   16   90000

In [17]:
df.loc[0:2]

        Name  Age  Salary
0      Rahul   16   90000
1      Janvi   17   70000
2  Aishwarya   18   50000

In [18]:
# iloc - index-value based index
df.iloc[2]
df.iloc[0:2] # start -stop-step

    Name  Age  Salary
0  Rahul   16   90000
1  Janvi   17   70000

### Filter Dataframe

In [19]:
df

        Name  Age  Salary
0      Rahul   16   90000
1      Janvi   17   70000
2  Aishwarya   18   50000
3     Simran   19   30000

In [23]:
df[df['Age']>= 18]

        Name  Age  Salary
2  Aishwarya   18   50000
3     Simran   19   30000

In [30]:
df[(df['Age'] >= 17) & (df['Salary'] > 50000)]

    Name  Age  Salary
1  Janvi   17   70000

In [32]:
df.where(df['Age']>=18, other= 'Not Eligible')

           Name           Age        Salary
0  Not Eligible  Not Eligible  Not Eligible
1  Not Eligible  Not Eligible  Not Eligible
2     Aishwarya            18         50000
3        Simran            19         30000

### Row and Columns - Operation (Add, update, delete)

#### Add

In [33]:
df

        Name  Age  Salary
0      Rahul   16   90000
1      Janvi   17   70000
2  Aishwarya   18   50000
3     Simran   19   30000

In [34]:
# add new column

df['Team'] = ["CEO", "MD", "MIS", "DA"]

df

        Name  Age  Salary Team
0      Rahul   16   90000  CEO
1      Janvi   17   70000   MD
2  Aishwarya   18   50000  MIS
3     Simran   19   30000   DA

In [ ]:
# add new column

df['Bonus'] = df['Salary']*0.2
print(df)


# add new row
df.loc[len(df)] = ['ABC',21,21000,'IT',2000]
print(df)

        Name  Age  Salary Team    Bonus
0      Rahul   16   90000  CEO  18000.0
1      Janvi   17   70000   MD  14000.0
2  Aishwarya   18   50000  MIS  10000.0
3     Simran   19   30000   DA   6000.0
        Name  Age  Salary Team    Bonus
0      Rahul   16   90000  CEO  18000.0
1      Janvi   17   70000   MD  14000.0
2  Aishwarya   18   50000  MIS  10000.0
3     Simran   19   30000   DA   6000.0
4        ABC   21   21000   IT   2000.0

#### update

In [39]:
# update value

df.loc[0,'Salary'] = 74000
df

        Name  Age  Salary Team    Bonus
0      Rahul   16   74000  CEO  18000.0
1      Janvi   17   70000   MD  14000.0
2  Aishwarya   18   50000  MIS  10000.0
3     Simran   19   30000   DA   6000.0
4        ABC   21   21000   IT   2000.0

In [40]:
# update value - using column value
df.loc[df.Name == "Rahul","Salary"] = 1000000
df

        Name  Age   Salary Team    Bonus
0      Rahul   16  1000000  CEO  18000.0
1      Janvi   17    70000   MD  14000.0
2  Aishwarya   18    50000  MIS  10000.0
3     Simran   19    30000   DA   6000.0
4        ABC   21    21000   IT   2000.0

### Delete

In [46]:
# delete value - row and column values
# axis = 0 (row), 1 (column)

df.drop(df[df['Name']== 'ABC'].index) # index used to capture entire row 
df

        Name  Age   Salary Team    Bonus
0      Rahul   16  1000000  CEO  18000.0
1      Janvi   17    70000   MD  14000.0
2  Aishwarya   18    50000  MIS  10000.0
3     Simran   19    30000   DA   6000.0

In [42]:
df[df.Name == 'ABC']

  Name  Age  Salary Team   Bonus
4  ABC   21   21000   IT  2000.0

In [ ]:
df.drop('Bonus', axis = 1) # dop column

        Name  Age   Salary Team
0      Rahul   16  1000000  CEO
1      Janvi   17    70000   MD
2  Aishwarya   18    50000  MIS
3     Simran   19    30000   DA

In [50]:
# drop multiple columns
df.drop(['Bonus','Team'], axis = 1)

        Name  Age   Salary
0      Rahul   16  1000000
1      Janvi   17    70000
2  Aishwarya   18    50000
3     Simran   19    30000