### Naive Bayes 

- is a machine algorithm based on supervise learning that can be used fo solving lassification problem
- it is probablistic classifier, which means it predicts based on the probability of the object
- Sample : {Head or Tales} if you toss a coin
- sample : {roll of dice 1,2,3,4,5,6}
- sample : {Toss of two coinf of getting HH, HT, TT, TH}

Naive + Bayes = works on conditionl probablity
[Naive : it makes the assumption that all attributes are independent of each other] > if someone say red fruit  + black seeds + sweet taste = "Watermelon" comes in mind
[Bayes : because it depends on the principle of Bayes Theorem]

for example:
"Congratulations you have won a lottery of 10 crore rupees."

probablity

congrats -- spam word / fake  -- Probablity 0.25
won -- spam word / fake -- Probablity  0.45
lottery -- Probablity   0.67
10 crore -- Probablity  0.80


probablity: 0.25+0.54+0.67+0.80 

#### use case
1. Face recognition
2. New categorization
3. Email Sapm 
4. weather forecast
5. image classifier

In [18]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [12]:
import pandas as pd

url = "https://raw.githubusercontent.com/sharmaroshan/Social-Networks-Ads/master/Social_Network_Ads.csv"
df = pd.read_csv(url)
df

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [13]:
df['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [14]:
df.drop('User ID', axis= 1, inplace = True)

In [15]:
df

     Gender   Age  EstimatedSalary  Purchased
0      Male  19.0          19000.0          0
1      Male  35.0          20000.0          0
2    Female  26.0          43000.0          0
3    Female  27.0          57000.0          0
4      Male  19.0          76000.0          0
..      ...   ...              ...        ...
395  Female  46.0          41000.0          1
396    Male  51.0          23000.0          1
397  Female  50.0          20000.0          1
398    Male  36.0          33000.0          0
399  Female  49.0          36000.0          1

[400 rows x 4 columns]

In [29]:
X = df[['Gender',	'Age',	'EstimatedSalary']]
y = df[['Purchased']]

In [30]:
X

     Gender   Age  EstimatedSalary
0         1  19.0          19000.0
1         1  35.0          20000.0
2         0  26.0          43000.0
3         0  27.0          57000.0
4         1  19.0          76000.0
..      ...   ...              ...
395       0  46.0          41000.0
396       1  51.0          23000.0
397       0  50.0          20000.0
398       1  36.0          33000.0
399       0  49.0          36000.0

[400 rows x 3 columns]

In [31]:
y

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [26]:
Gender = LabelEncoder()

In [27]:
df['Gender'] = Gender.fit_transform(df['Gender'])

In [28]:
df

     Gender   Age  EstimatedSalary  Purchased
0         1  19.0          19000.0          0
1         1  35.0          20000.0          0
2         0  26.0          43000.0          0
3         0  27.0          57000.0          0
4         1  19.0          76000.0          0
..      ...   ...              ...        ...
395       0  46.0          41000.0          1
396       1  51.0          23000.0          1
397       0  50.0          20000.0          1
398       1  36.0          33000.0          0
399       0  49.0          36000.0          1

[400 rows x 4 columns]

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [33]:
len(X_train)

320

In [34]:
len(X_test)

80

In [36]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [37]:
model.fit(X_train, y_train)

/Users/rahulg/Downloads/python-revision-experiments/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB()

In [38]:
model.predict(X_test)

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [40]:
X_test

     Gender   Age  EstimatedSalary
209       0  46.0          22000.0
280       0  59.0          88000.0
33        0  28.0          44000.0
210       0  48.0          96000.0
93        0  29.0          28000.0
..      ...   ...              ...
246       0  35.0          50000.0
227       1  56.0         133000.0
369       0  54.0          26000.0
176       0  35.0          47000.0
289       0  37.0          78000.0

[80 rows x 3 columns]

In [41]:
model.score(X_test, y_test)

0.9375