# Pandas

- used to data manipulate and analysis
- effective on structure data like table based one's

In [5]:
!pip install pandas
!pip install --upgrade pip

Collecting pandas
  Downloading pandas-3.0.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 1.0 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numpy>=1.26.0 in /Users/rahulg/Downloads/python-revision-experiments/.venv/lib/python3.12/site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rahulg/Downloads/python-revision-experiments/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/rahulg/Downloads/python-revision-experiments/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp312-cp312-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 5.7 MB/s eta 0:00:0000:0100:01
Installing collected packages: pandas
Successfully installed pandas-3.0.0

[notice] A new release of pip is available: 24.0 -> 26.0
[notice] To update, run: pip install --upgrade pip
Requirement already satisfied: pip in /Users/rahulg/Downloads/python-revision-experiments/.venv/lib/python3.12/site-packages (24.0)
Collecting pip
  Downloading pip-26.0-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-26.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.2 MB/s eta 0:00:0000:0100:01
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0
Successfully installed pip-26.0

In [1]:
# import pandas as pd
import pandas as pd

In [8]:
# check the version of pandas

print(pd.__version__)

3.0.0

### Dataframe

- frame that has rows and column

- Extra information: Shift + Tab (enables the code writing info) [HP]
- In MacOS : Cmd + shift + space

In [9]:
df = pd.DataFrame([1,2,3])
print(df)

   0
0  1
1  2
2  3

In [12]:
df = pd.DataFrame([11,22,33], columns= ["Col_Name"])
print(df)
#          column
#   row      0
#    0.      11
#    1.      22
#    2.      33

print(type(df))

   Col_Name
0        11
1        22
2        33
<class 'pandas.DataFrame'>

### creating Dataframe

In [7]:
data = {
    'Name' : ["Rahul", "Janvi","Aishwarya","Simran"],
    "Age" : [16,17,18,19],
    "Salary" : [90000, 70000, 50000, 30000]
}

df = pd.DataFrame(data)
print(df)
print(type(df))

        Name  Age  Salary
0      Rahul   16   90000
1      Janvi   17   70000
2  Aishwarya   18   50000
3     Simran   19   30000
<class 'pandas.DataFrame'>

### Basic Dataframe Understanding

In [34]:
df.head(2) # top rows

    Name  Age  Salary
0  Rahul   16   90000
1  Janvi   17   70000

In [36]:
df.tail(2) # last rows

        Name  Age  Salary
2  Aishwarya   18   50000
3     Simran   19   30000

In [20]:
df.shape # tells row x column

(4, 3)

In [21]:
df.columns # columns name

Index(['Name', 'Age', 'Salary'], dtype='str')

In [37]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace= True) # rename of the column

# use of inplace = True {made changes in the origin data}

In [38]:
df

        Name  Age  Monthly_Salary
0      Rahul   16           90000
1      Janvi   17           70000
2  Aishwarya   18           50000
3     Simran   19           30000

In [39]:
df.info() # infomation about the table

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [32]:
df.describe() # statistical summary of the table

             Age  Monthly_Salary
count   4.000000        4.000000
mean   17.500000    60000.000000
std     1.290994    25819.888975
min    16.000000    30000.000000
25%    16.750000    45000.000000
50%    17.500000    60000.000000
75%    18.250000    75000.000000
max    19.000000    90000.000000

### Save and load data from csv

In [ ]:
df.to_csv('testData.csv', index= False) # export into csv & also removed the index out of it

In [2]:
loaddf = pd.read_csv('testData.csv') # import from csv 
loaddf

        Name  Age  Salary
0      Rahul   16   90000
1      Janvi   17   70000
2  Aishwarya   18   50000
3     Simran   19   30000

### Rows and Column Selection

In [9]:
# select column

df['Name'] # single column

0        Rahul
1        Janvi
2    Aishwarya
3       Simran
Name: Name, dtype: str

In [11]:
df[['Name','Salary']]   # mutiple columns

        Name  Salary
0      Rahul   90000
1      Janvi   70000
2  Aishwarya   50000
3     Simran   30000

In [14]:
# slect rows. : loc = label based index 
df.loc[df.Name=="Janvi"]    # location index based on name

df.loc[(df.Name=='Rahul') & (df.Salary>= 50000)]

    Name  Age  Salary
0  Rahul   16   90000

In [17]:
df.loc[0:2]

        Name  Age  Salary
0      Rahul   16   90000
1      Janvi   17   70000
2  Aishwarya   18   50000

In [18]:
# iloc - index-value based index
df.iloc[2]
df.iloc[0:2] # start -stop-step

    Name  Age  Salary
0  Rahul   16   90000
1  Janvi   17   70000

### Filter Dataframe

In [19]:
df

        Name  Age  Salary
0      Rahul   16   90000
1      Janvi   17   70000
2  Aishwarya   18   50000
3     Simran   19   30000

In [23]:
df[df['Age']>= 18]

        Name  Age  Salary
2  Aishwarya   18   50000
3     Simran   19   30000

In [30]:
df[(df['Age'] >= 17) & (df['Salary'] > 50000)]

    Name  Age  Salary
1  Janvi   17   70000

In [32]:
df.where(df['Age']>=18, other= 'Not Eligible')

           Name           Age        Salary
0  Not Eligible  Not Eligible  Not Eligible
1  Not Eligible  Not Eligible  Not Eligible
2     Aishwarya            18         50000
3        Simran            19         30000

### Row and Columns - Operation (Add, update, delete)

#### Add

In [33]:
df

        Name  Age  Salary
0      Rahul   16   90000
1      Janvi   17   70000
2  Aishwarya   18   50000
3     Simran   19   30000

In [8]:
# add new column

df['Team'] = ["CEO", "MD", "MIS", "DA"]

df

        Name  Age  Salary Team
0      Rahul   16   90000  CEO
1      Janvi   17   70000   MD
2  Aishwarya   18   50000  MIS
3     Simran   19   30000   DA

In [ ]:
# add new column

df['Bonus'] = df['Salary']*0.2
print(df)


# add new row
df.loc[len(df)] = ['ABC',21,21000,'IT',2000]
print(df)

        Name  Age  Salary Team    Bonus
0      Rahul   16   90000  CEO  18000.0
1      Janvi   17   70000   MD  14000.0
2  Aishwarya   18   50000  MIS  10000.0
3     Simran   19   30000   DA   6000.0
        Name  Age  Salary Team    Bonus
0      Rahul   16   90000  CEO  18000.0
1      Janvi   17   70000   MD  14000.0
2  Aishwarya   18   50000  MIS  10000.0
3     Simran   19   30000   DA   6000.0
4        ABC   21   21000   IT   2000.0

#### update

In [39]:
# update value

df.loc[0,'Salary'] = 74000
df

        Name  Age  Salary Team    Bonus
0      Rahul   16   74000  CEO  18000.0
1      Janvi   17   70000   MD  14000.0
2  Aishwarya   18   50000  MIS  10000.0
3     Simran   19   30000   DA   6000.0
4        ABC   21   21000   IT   2000.0

In [9]:
# update value - using column value
df.loc[df.Name == "Rahul","Salary"] = 1000000
df

        Name  Age   Salary Team
0      Rahul   16  1000000  CEO
1      Janvi   17    70000   MD
2  Aishwarya   18    50000  MIS
3     Simran   19    30000   DA

### Delete

In [10]:
# delete value - row and column values
# axis = 0 (row), 1 (column)

df.drop(df[df['Name']== 'ABC'].index) # index used to capture entire row 
df

        Name  Age   Salary Team
0      Rahul   16  1000000  CEO
1      Janvi   17    70000   MD
2  Aishwarya   18    50000  MIS
3     Simran   19    30000   DA

In [42]:
df[df.Name == 'ABC']

  Name  Age  Salary Team   Bonus
4  ABC   21   21000   IT  2000.0

In [ ]:
df.drop('Bonus', axis = 1) # drop column

        Name  Age   Salary Team
0      Rahul   16  1000000  CEO
1      Janvi   17    70000   MD
2  Aishwarya   18    50000  MIS
3     Simran   19    30000   DA

In [50]:
# drop multiple columns
df.drop(['Bonus','Team'], axis = 1)

        Name  Age   Salary
0      Rahul   16  1000000
1      Janvi   17    70000
2  Aishwarya   18    50000
3     Simran   19    30000

### sort values

In [ ]:
df.sort_values('Salary') # ascending approach

        Name  Age  Salary
3     Simran   19   30000
2  Aishwarya   18   50000
1      Janvi   17   70000
0      Rahul   16   90000

In [ ]:
df.sort_values('Salary',ascending=False)    # descending approach

        Name  Age  Salary
0      Rahul   16   90000
1      Janvi   17   70000
2  Aishwarya   18   50000
3     Simran   19   30000

### working with date values

In [23]:
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03']

In [24]:
df # YYY - MM - DD [HH:MM:SS]

0                                   2024-01-01 00:00:00
1                                   2024-01-15 00:00:00
2                                   2024-03-28 00:00:00
3                                   2024-03-03 00:00:00
DOJ    [2024-01-01, 2024-01-15, 2024-03-28, 2024-03-03]
Name: DOJ, dtype: object

In [ ]:
df['DOJ'].dtype

In [26]:
# convert to datetime format DOJ

df['DOJ'] = pd.to_datetime(df['DOJ'])
df['DOJ']

DatetimeIndex(['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03'], dtype='datetime64[us]', freq=None)

In [18]:
df1 = df
df1['DOJ'] = ['01-01-2025', '15-01-2025', '28-03-2025', '03-03-2025']
df1

0                                   2024-01-01 00:00:00
1                                   2024-01-15 00:00:00
2                                   2024-03-28 00:00:00
3                                   2024-03-03 00:00:00
DOJ    [01-01-2025, 15-01-2025, 28-03-2025, 03-03-2025]
Name: DOJ, dtype: object

In [ ]:
df1['DOJ'] = pd.to_datetime(df1['DOJ'], format= '%d-%m-%y')
df1['DOJ'].dtype

In [32]:
# extract year, month, week, day
df['DOJ'].year
df['DOJ'].month
df['DOJ'].day
df['DOJ'].day_name()

Index(['Monday', 'Monday', 'Thursday', 'Sunday'], dtype='str')

In [ ]:
df['DOJ']+pd.Timedelta(days=90) # to add certain days to the date

DatetimeIndex(['2024-03-31', '2024-04-14', '2024-06-26', '2024-06-01'], dtype='datetime64[us]', freq=None)

### handling missing values

In [12]:
df

        Name  Age   Salary Team
0      Rahul   16  1000000  CEO
1      Janvi   17    70000   MD
2  Aishwarya   18    50000  MIS
3     Simran   19    30000   DA

In [ ]:
df.isnull()     # determine the null value

    Name    Age  Salary   Team
0  False  False   False  False
1  False  False   False  False
2  False  False   False  False
3  False  False   False  False

In [14]:
import numpy as np
df.loc[df.Name == "Rahul", 'Salary'] = np.nan

In [15]:
df

        Name  Age   Salary Team
0      Rahul   16      NaN  CEO
1      Janvi   17  70000.0   MD
2  Aishwarya   18  50000.0  MIS
3     Simran   19  30000.0   DA

In [ ]:
df.isnull() # determine whether null

    Name    Age  Salary   Team
0  False  False    True  False
1  False  False   False  False
2  False  False   False  False
3  False  False   False  False

In [ ]:
df.isnull().sum()   # calculate the overall null

Name      0
Age       0
Salary    1
Team      0
dtype: int64

In [ ]:
df.fillna(0)    # filled the null with zero

        Name  Age   Salary Team
0      Rahul   16      0.0  CEO
1      Janvi   17  70000.0   MD
2  Aishwarya   18  50000.0  MIS
3     Simran   19  30000.0   DA

### Aggregation and groupby

In [20]:
df['Team'].value_counts()

Team
CEO    1
MD     1
MIS    1
DA     1
Name: count, dtype: int64

In [ ]:
df[df['Month']==1].value_counts()   # frequency of the value

In [ ]:
df.groupby('Month')['Salary'].sum() # aggregation based monthly wise salary

In [ ]:
df.groupby('Month').agg({'Salary':'mean', 'Name':'count'})  # mutiple column based aggregation

### Concatenate and merge DataFrame(Joins)

In [22]:
df1 = pd.DataFrame({
    'ID':[1,2,3],
    'Name' : ['A','B','C']
})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [23]:
df2 = pd.DataFrame({
    'ID':[1,2,2,4],
    'Score' : [88,96,77,79]
})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [ ]:
# concatenate the created DataFrame

pd.concat([df1,df2],axis = 0)   # vertical table join/ row level / top on top

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [ ]:
pd.concat([df1,df2],axis = 1) # horizontal table join/ column level / side on side

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [ ]:
# merge table

pd.merge(df1, df2, how = "inner", on="ID")

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

### AI & ChatGPT

In [ ]:
filtered = df.query("Month == 1 and Salary > 70000")
print(filtered)

In [27]:
# create a realistic sales dataset you can practice many pivot questions on.

import pandas as pd

data = {
    "Date": [
        "2024-01-01","2024-01-02","2024-01-03","2024-01-04","2024-01-05",
        "2024-01-06","2024-01-07","2024-01-08","2024-01-09","2024-01-10",
        "2024-01-11","2024-01-12","2024-01-13","2024-01-14","2024-01-15"
    ],
    "City": [
        "Mumbai","Mumbai","Delhi","Delhi","Pune",
        "Pune","Mumbai","Delhi","Pune","Mumbai",
        "Delhi","Mumbai","Pune","Delhi","Mumbai"
    ],
    "Product": [
        "Laptop","Mobile","Laptop","Tablet","Mobile",
        "Laptop","Tablet","Mobile","Tablet","Laptop",
        "Laptop","Mobile","Laptop","Tablet","Mobile"
    ],
    "Salesperson": [
        "Rahul","Amit","Rahul","Sneha","Amit",
        "Sneha","Rahul","Amit","Sneha","Rahul",
        "Amit","Sneha","Rahul","Amit","Sneha"
    ],
    "Units": [5,8,4,6,7,3,5,9,4,6,8,7,2,5,9],
    "Revenue": [50000,80000,40000,36000,56000,30000,25000,90000,28000,60000,80000,70000,20000,30000,90000]
}

df = pd.DataFrame(data)
df["Date"] = pd.to_datetime(df["Date"])

df

         Date    City Product Salesperson  Units  Revenue
0  2024-01-01  Mumbai  Laptop       Rahul      5    50000
1  2024-01-02  Mumbai  Mobile        Amit      8    80000
2  2024-01-03   Delhi  Laptop       Rahul      4    40000
3  2024-01-04   Delhi  Tablet       Sneha      6    36000
4  2024-01-05    Pune  Mobile        Amit      7    56000
5  2024-01-06    Pune  Laptop       Sneha      3    30000
6  2024-01-07  Mumbai  Tablet       Rahul      5    25000
7  2024-01-08   Delhi  Mobile        Amit      9    90000
8  2024-01-09    Pune  Tablet       Sneha      4    28000
9  2024-01-10  Mumbai  Laptop       Rahul      6    60000
10 2024-01-11   Delhi  Laptop        Amit      8    80000
11 2024-01-12  Mumbai  Mobile       Sneha      7    70000
12 2024-01-13    Pune  Laptop       Rahul      2    20000
13 2024-01-14   Delhi  Tablet        Amit      5    30000
14 2024-01-15  Mumbai  Mobile       Sneha      9    90000

In [28]:
pd.pivot_table(df, values="Revenue", index="City", aggfunc="sum")

        Revenue
City
Delhi    276000
Mumbai   375000
Pune     134000

In [29]:
pd.pivot_table(df, values="Revenue", index="City", columns="Product", aggfunc="sum")

Product  Laptop  Mobile  Tablet
City
Delhi    120000   90000   66000
Mumbai   110000  240000   25000
Pune      50000   56000   28000

In [30]:
pd.pivot_table(df, values="Units", index="Salesperson", aggfunc="count")

             Units
Salesperson
Amit             5
Rahul            5
Sneha            5

In [31]:
pd.pivot_table(df, values="Units", index="Product", aggfunc="mean")

            Units
Product
Laptop   4.666667
Mobile   8.000000
Tablet   5.000000

In [32]:
pd.pivot_table(
    df,
    values="Revenue",
    index="City",
    columns="Product",
    aggfunc=["sum","mean","count"]
)

            sum                    mean                    count
Product  Laptop  Mobile Tablet   Laptop   Mobile   Tablet Laptop Mobile Tablet
City
Delhi    120000   90000  66000  60000.0  90000.0  33000.0      2      1      2
Mumbai   110000  240000  25000  55000.0  80000.0  25000.0      2      3      1
Pune      50000   56000  28000  25000.0  56000.0  28000.0      2      1      1

In [33]:
pd.pivot_table(
    df,
    values="Revenue",
    index=df["Date"].dt.month,
    columns="City",
    aggfunc="sum"
)

City   Delhi  Mumbai    Pune
Date
1     276000  375000  134000